baseURL = "https://z1ko.github.io/z1blog.github.io/"
languageCode = "en-us"
title = "z1blog"
theme = "risotto"
paginate = 5

[params]

# Contenuto principale
contentTypeName = "posts"

# Configurazione del tema
themeColor = "pink"
fullWidthTheme = false
centerTheme = true
